### ISSUE TITLE
Error on Windows with JuceDemoPlugin

### ISSUE THREAD

**Issue by alfonso73** [WeAreROLI/JUCE#161]
Hi, with Juce 4.3.1.
On Windows 7 64 bit using VS2015 as a target.
When i load JuceDemoPlugin ( the one in C:\Program Files\JUCE\examples\audio plugin demo )
in the Build tag of Projucer i have this error

error: C:\Program Files\Juce\examples\audio plugin demo\JuceLibraryCode\juce_audio_plugin_client_VST3.cpp: pragma comment requires parenthesized identifier and optional string

the code line at wich the error points to is

#pragma comment(linker, "/EXPORT:" __FUNCTION__ "=" __FUNCDNAME__)

**Comment by tpoole** [comment]
> When i load JuceDemoPlugin ( the one in C:\Program Files\JUCE\examples\audio plugin demo )
in the Build tag of Projucer

Could you please provide some more details? What does "load" mean?

**Comment by alfonso73** [comment]
Hi Tom, it happens when i open the JuceDemoPlugin with the Projucer. After the progress indicator in the Build tag has finished working the error appears in the Build tag area.

**Comment by ed95** [comment]
The build error has been fixed in the latest version of JUCE, but it isn't possible to run the `AudioPluginDemo` in the Projucer's live-build engine as it does not have a default constructor. You should open the project in Visual Studio and build the standalone target if you want to test the plug-in out.
