### ISSUE TITLE
Projucer (slow saving / crashing): Add option to save project only for current or selected platform

### ISSUE THREAD

**Issue by benkuper** [WeAreROLI/JUCE#191]
When using Projucer on Windows with a VS export and an XCode export, and they don't have the same paths for modules.
Saving the project on Windows is very slow and often result in the Projucer crashing or not responding.

I launched from VS in debug mode and it seems that the problem comes from the File class that doesn't find any files when saving the XCode exporter (which is quite normal), i added this line in juce_ProjectSaver, at line 648 :

if ((exporter->isOSX() || exporter->isWindows()) && !exporter->canLaunchProject()) return; //avoid creating osx project from win and vice-versa

i just wanted to avoid creating osx from win, or win from osx, but i still want to be able to create the linuxMakeFile from win or from osx.

There must be something more clever than this but it reduced the saving time of a quite big project in Windows from 30 seconds to less than 1 seconds.

What would be cool is if from a platform, we can choose which exporter to save.

**Comment by ed95** [comment]
Slow Windows project saving has been fixed in commit [f50aaab](https://github.com/WeAreROLI/JUCE/commit/f50aaab946b1c4c1d576448223bbd39218605528) and the ability to save single exporters has been added in commit [90fbed7](https://github.com/WeAreROLI/JUCE/commit/90fbed7889368a3dd23f8d92c21e1fc1fa2cf604)
