### ISSUE TITLE
ListBox: when setting setMultipleSelectionEnabled(false), setClickingTogglesRowSelection(true) does not produce row toggling.

### ISSUE THREAD

**Issue by mathieu-b** [WeAreROLI/JUCE#233]
To reproduce the issue, call the following on a `ListBox` instance:
```
listbox->setMultipleSelectionEnabled (false);
listbox->setClickingTogglesRowSelection (true); // this sets alwaysFlipSelection to true
```
When interacting with the `ListBox`, toggling the current selection will be impossible: once a row is selected, it will be impossible to have _no rows_ selected.

Basically it is impossible to have a de-select / no-selection capability. 

To fix this, the code starting [from this line in juce_ListBox.cpp](https://github.com/WeAreROLI/JUCE/blob/03de7b468f35dd8496f8984f9701db619670bddd/modules/juce_gui_basics/widgets/juce_ListBox.cpp#L602) should be replaced by the following:

```
    // ...
    else if ((! mods.isPopupMenu()) || ! isRowSelected (row))
    {
        if (alwaysFlipSelection && isRowSelected (row))
        {
            flipRowSelection (row);
        }
        else
        {
            selectRowInternal (row, false, ! (multipleSelection && (! isMouseUpEvent) && isRowSelected (row)), true);
        }
    }
```

**Comment by ed95** [comment]
The [documentation for setClickingTogglesRowSelection()](https://github.com/WeAreROLI/JUCE/blob/develop/modules/juce_gui_basics/widgets/juce_ListBox.h#L228) states that "This only has an effect if multiple selection is also enabled" so I'm hesitant to change the behaviour of ListBox as it may break code that people have written based on this. Adding deselection on mouse-click is quite easy to implement in your ListBoxModel though - I've pasted in a simple example for how to do it below (the logic in listBoxItemClicked() is a bit weird because the ListBox selects the item before the ListBoxModel callback).

    struct CustomListBoxModel : ListBoxModel
    {
        CustomListBoxModel (ListBox& o) : owner (o) {}
        int getNumRows() override { return 50; }

        void paintListBoxItem (int rowNumber, Graphics& g, int, int, bool rowIsSelected) override
        {
            g.fillAll (coloursArray.getUnchecked (rowNumber % 3).withAlpha (rowIsSelected ? 1.0f : 0.2f));
        }
        
        void listBoxItemClicked (int row, const MouseEvent&) override
        {
            if (lastSelected == row)
            {
                owner.deselectRow (row);
                lastSelected = -1;
            }
            else
            {
                lastSelected = row;
            }
        }
        
        ListBox& owner;
        int lastSelected = -1;
        Array<Colour> coloursArray = { Colours::red, Colours::orange, Colours::blue };
    };

**Comment by mathieu-b** [comment]
Hi @ed95, I see.

Thanks for the suggestion.

Regards.
