### ISSUE TITLE
juce_blocks_basics is missing a dependency on juce_graphics

### ISSUE THREAD

**Issue by Adjacence** [WeAreROLI/JUCE#470]
The juce_blocks_basics module contains code that is dependent on juce_graphics, but there is no inclusion of juce_graphics.h in juce_blocks_basics.h nor is juce_graphics listed as a dependency in the documentation. The module cannot be built in isolation without manually adding the header include directive.

**Comment by McMartin** [comment]
@Adjacence very nice catch 👏 
I can add that `juce_blocks_basics` doesn't build because it uses the `Point` and `Rectangle` class templates, which are defined in `juce_graphics`.
Other interesting point: `juce_blocks_basics` is permissively licensed under the terms of the ISC license, but `juce_graphics` is not...

**Comment by ed95** [comment]
Thanks for reporting, this has been fixed in [5189b4b](https://github.com/WeAreROLI/JUCE/commit/5189b4bbd983fe58854cc2078ceea8aaabc97c55) (the commit message should read juce_graphics and not juce_gui_basics, however).
