### ISSUE TITLE
DrawableButton::ButtonStyle::ImageRaw doesn't work for scalable graphics

### ISSUE THREAD

**Issue by jamiebullock** [WeAreROLI/JUCE#509]
Steps to reproduce:
- Create an instance of `DrawableButton` with a `ButtonStyle` of` ImageRaw`
- Create a scalable `Drawable *` e.g. from an SVG
- Resize the drawable using `Drawable::setTransformToFit()`
- Add the drawable to the button using `DrawableButton::setImages()`

Expected behaviour:
- The image is the size and position set with `setTransformToFit()`

Actual behaviour:
- The image is the incorrect size and position

Reason:
- `DrawableButton::resized()` resets the transform on the drawable passed in for the image:

```
void DrawableButton::resized()
{
    Button::resized();

    if (currentImage != nullptr)
    {
        if (style == ImageRaw)
            currentImage->setOriginWithOriginalSize (Point<float>());  // <---- HERE
        else
            currentImage->setTransformToFit (getImageBounds(),
                                             style == ImageStretched ? RectanglePlacement::stretchToFit
                                                                     : RectanglePlacement::centred);
    }
}
```

**Comment by ed95** [comment]
I've removed that line on the develop branch in commit [a529fbb](https://github.com/WeAreROLI/JUCE/commit/a529fbbf473fcfd3c8950dfa93b1e49e3cf0d8ab) as I can't really see what it was doing other than removing transforms that have been set on the Drawable which, as you say, is probably not the expected behaviour. Thank you for the detailed report.
