### ISSUE TITLE
Android: Back button stops working

### ISSUE THREAD

**Issue by extreamsd** [WeAreROLI/JUCE#533]
1) Although it doesn’t crash anymore in the developer branch, it stops working rather fast: take the NativeAndroidJuceSample, add a GUI component (NewComponent) and put a rotary slider on it. Then instead of ‘Slider juceComponent’ in NativeAndroidJuceActivity.cpp, use NewComponent juceComponent; and include the header.
The back button stops working after moving the slider. When pushing the button to remove the Juce component, you can use the back button.

  2) the expected behaviour

The back button should always work

  3) the operating system

Likely any Android version, but tested on Android 8.0.

  4) the architecture (32-bit or 64-bit)

32-bit

**Comment by ed95** [comment]
This should now be fixed in [937991c](https://github.com/WeAreROLI/JUCE/commit/937991cc83d28d54bd52813f103964721c4cf911). Pressing the back button on Android will now call `Activity.finish()` unless `JUCEApplicationBase::backButtonPressed()` has been overridden to do some custom back button press handling and returns `true`. Can you see if this has fixed the issue for you?
